### ISSUE TITLE
Segmentation fault when editing a stair-like line.

### ISSUE THREAD

**Issue by jabozzo** [RTimothyEdwards/XCircuit#2] opened 2020-01-26 22:21 UTC
**System**: Ubuntu 18.04.3 LTS
**Version**: Xcircuit v3.8 rev 78 (installed via apt)
**Bug**: Xcircuit crashes when editing a stair-like line. Console says `Segmentation fault (core dumped)`
**Steps to reproduce**:
- Open a terminal
- Run xcircuit
- Draw a line with a stair shape. In the example: `[(0,0), (32,0), (32,32), (64,32), (64,64)]`
- Edit the line and align one of the vertical slopes of the stair to another vertical slope, eliminating a step. In the example: move `(32,0)` to `(64,0)`
- Click to move to the next vertex, which is on the same position as the next vertex after itself. Move the vertex so the manhattan line transforms into a diagonal line. In the example: move `(64,32)` back to `(32,32)`
- Click to move to the next vertex, which is on the same position as the previous. Any movement will make the line move erratically. Example move `(32,32)` to `(64,32)`.
- Click to move to the next vertex.
- Xcircuit crashes

Images are provided as an example. The red crosshair indicates where the cursor started. The blue crosshair indicates where the cursor ended and a click was performed.

![0 - original line](https://user-images.githubusercontent.com/9649979/73142711-c7c03a00-4070-11ea-95d7-66ba7cdc3b77.png)
![1 - first click](https://user-images.githubusercontent.com/9649979/73142712-c858d080-4070-11ea-94b1-c8fe61d758a0.png)
![2 - second click](https://user-images.githubusercontent.com/9649979/73142713-c858d080-4070-11ea-8f63-34ed5e519bee.png)
![3 - third click](https://user-images.githubusercontent.com/9649979/73142714-c858d080-4070-11ea-98aa-375403354ff5.png)

**Comment by RTimothyEdwards** [comment] 2020-01-27 14:00
I cannot reproduce the crash condition, but I can reproduce some aspects of the behavior;  specifically, for me, if I do the above steps, I get into a state where clicking the left mouse button no longer moves to the next point;  it's stuck on the same point.  The segfault is probably somewhat OS (or gcc) dependent, and might be caused by use of an uninitialized variable or something like that.  I will track down the problem that I see, and once I have that fixed, you can test and see if that also fixes the segfault (I should be able to tell once I've found the problem, if it could potentially cause a segfault).

Thanks for isolating the problem nicely.

Regards,
Tim

**Comment by RTimothyEdwards** [comment] 2020-01-27 19:37
If you can do two things for me:  (1) Repeat this with Options->Elements->Polygon Edit set to "Normal Edit".  (2) Run under the gdb debugger and report which line it crashes on (use gdb on xcircexec, since xcircuit itself is a script, not an executable).

The behavior with the point advance getting stuck on a point clearly has to do with the X vs. Y movement restriction of the "manhattan edit" mode.  Since I can't make it crash on my computer, I'm wondering if the crash is related to the stuck position of the edit point, or if it is something different.

**Comment by jabozzo** [comment] 2020-01-27 20:18
No problem, I'll test it as soon as I arrive home

**Comment by jabozzo** [comment] 2020-01-28 00:42
I did (1), there were no problems even overlapping points on top of each other. For (2), the apt version of xcircuit ships without debugging symbols, so I'll have to first compile xcircuit and the test it.

This week I have some time-critical things to do so probably I will come back on the weekend with the results of (2).

**Comment by RTimothyEdwards** [comment] 2020-01-28 02:39
I found the problem with getting stuck on degenerate points.  I see nothing that would cause a segfault, though, so I am pushing the fix and will also wait and not close this issue until I have seen what you get from running under the debugger.  The update will get mirrored to the git repo overnight (in about 6 hours).

**Comment by RTimothyEdwards** [comment] 2020-02-04 12:53
Should I close this issue, or are you still seeing problems?

**Comment by jabozzo** [comment] 2020-02-04 13:56
Sorry, I have not been able to test it yet. By tomorrow I'll be able to see if the problem persists.

**Comment by jabozzo** [comment] 2020-02-05 00:57
I've tested it. It does not crash and it works  :+1:

**Closed** 2020-02-05 00:58 UTC
